/*
    CODED BY ANGEL BERLANGA
    EMAIL: angel.tigre@hotmail.com
    GITHUB: https://github.com/EddyBer16
    REPOSITORY OF THESE PRACTICES: https://github.com/EddyBer16/RobotCPrograms
*/

#pragma config(Sensor, S1,     Sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ColorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     Gyroscope,      sensorEV3_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void displaySensorsValues() {
    while(true) {
        displaySensorValues(line1, S1);
        displaySensorValues(line2, S2);
        displaySensorValues(line3, S3);
    }
}

task main() {
    displaySensorsValues();
}
